### ISSUE TITLE
Windows 运行pcap2socks-gui.exe出现错误

### ISSUE THREAD

**Issue by herman6888** [zhxie/pcap2socks-gui#1]
Windows 运行pcap2socks-gui.exe出现错误：
The code execution cannot proceed because packet.dll was not found. Reinstalling the program may fix this problem.

**Comment by herman6888** [comment]
Solved by installed WinPcap

**Comment by zhxie** [comment]
Thanks for the feedback. In updates, I will also package the necessary DLLs into the release.

---

感谢反馈。在之后的更新中，我也将把必要的DLL打包进发布中。

**Comment by caidingding233** [comment]
> Thanks for the feedback. In updates, I will also package the necessary DLLs into the release.
> 
> 感谢反馈。在之后的更新中，我也将把必要的DLL打包进发布中。

哥你好像也没有更了
bro update it plz

**Comment by zhxie** [comment]
> > Thanks for the feedback. In updates, I will also package the necessary DLLs into the release.
> > 感谢反馈。在之后的更新中，我也将把必要的DLL打包进发布中。
> 
> 哥你好像也没有更了 bro update it plz

pcap2socks使用的技术栈已经严重过时了，项目亦不再积极维护，在性能以及对新OS的支持等方面或存在缺陷。请尽可能使用通过TUN/TAP等虚拟网络设备以及smoltcp、gVisor Networking等协议栈构建的应用。

如你依然需要使用，请参考[Dependencies](https://github.com/zhxie/pcap2socks-gui?tab=readme-ov-file#dependencies)安装必须的依赖项。
