### ISSUE TITLE
macOS Build

### ISSUE THREAD

**Issue by xinyangt9** [zhxie/pcap2socks-gui#2]
之后的Releases如果方便的话能否提供macOS的预编译版本 :)

**Comment by zhxie** [comment]
Sorry, but because I don’t have any macOS device, I cannot compile and test the application. I don't know how to deploy and distribute GUI programs that require root privileges on macOS😔.

---

很抱歉，但因为我没有 macOS 的设备，所以无法进行编译与测试。我不知道需要 root 权限的 GUI 程序如何在 macOS 上部署与分发😔。

**Comment by xinyangt9** [comment]
Got it. Thanks anyway.
