### ISSUE TITLE
win10 自动退出

### ISSUE THREAD

**Issue by RockyLOMO** [zhxie/pcap2socks-gui#3]
兼容模式也不行

**Comment by zhxie** [comment]
pcap2socks GUI requires Windows 10 with EdgeHTML support. If you meets the requirement, please check the [Troubleshoot](https://github.com/zhxie/pcap2socks-gui#troubleshoot) and [Known Issues and Limitations of web-view](https://github.com/Boscop/web-view#known-issues-and-limitations).

---

pcap2socks GUI 需要运行于具有 EdgeHTML 支持的 Windows 10。请确认 [Troubleshoot](https://github.com/zhxie/pcap2socks-gui#troubleshoot) 与 [web-view 的 Known Issues and Limitations of web-view](https://github.com/Boscop/web-view#known-issues-and-limitations) 一节。
